runtime: python311

# Cloud Run buildpack configuration
env_variables:
  PORT: "8000"
  PYTHONPATH: "/workspace"
  
# Gunicorn configuration for production
entrypoint: "adk web --host 0.0.0.0 --port $PORT"

# Resource allocation
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  
resources:
  cpu: 2
  memory_gb: 2

# Health checks (health endpoint exists at /health)
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
  
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2