# Fixed Cloud Build configuration 
steps:
  # Step 1: Generate requirements.txt
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Installing uv for requirements generation..."
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$$HOME/.cargo/bin:$$PATH"
        
        echo "📋 Generating requirements.txt..."
        uv export --format requirements-txt --locked --no-dev --no-hashes > requirements.txt || echo "Failed to generate with uv, creating minimal requirements.txt"
        
        # Fallback minimal requirements if uv fails
        if [ ! -f "requirements.txt" ] || [ ! -s "requirements.txt" ]; then
          echo "Creating fallback requirements.txt..."
          cat > requirements.txt << EOF
        fastapi==0.104.1
        uvicorn==0.24.0
        google-adk==1.0.0
        openai==1.3.8
        replicate==0.20.0
        pydantic==2.5.0
        requests==2.31.0
        EOF
        fi
        
        # Remove editable installs
        sed -i '/^-e \./d' requirements.txt
        
        echo "✅ Requirements.txt generated ($(wc -l < requirements.txt) lines)"
        head -10 requirements.txt

  # Step 2: Build Docker image (simplified)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/adk-branding-assistant:latest'
      - '-f'
      - 'Dockerfile.simple'
      - '.'

  # Step 3: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/adk-branding-assistant:latest']

  # Step 4: Deploy to Cloud Run (without secret conflicts)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'adk-branding-assistant'
      - '--image=gcr.io/$PROJECT_ID/adk-branding-assistant:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--max-instances=10'
      - '--port=8000'
      - '--quiet'

# Specify timeout
timeout: 1800s

# Define build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Remove secret management - let GitHub Actions handle this
substitutions:
  _SERVICE_NAME: 'adk-branding-assistant'
  _REGION: 'us-central1' 