name: Test Minimal Deployment

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ test-minimal ]

jobs:
  test-minimal-deploy:
    name: Test Minimal Deploy to Google Cloud
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test-minimal' || github.event_name == 'workflow_dispatch'
    environment: production
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/1018023867491/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-deployer@my-ai-projects-422803.iam.gserviceaccount.com'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Test minimal build locally first
      run: |
        echo "🧪 Testing minimal Dockerfile build..."
        
        # Replace the main Dockerfile with minimal one for testing
        cp Dockerfile.minimal Dockerfile
        cp pyproject.minimal.toml pyproject.toml
        
        echo "📋 Using minimal dependencies:"
        cat pyproject.toml
        
        echo "🐳 Dockerfile content:"
        cat Dockerfile
    
    - name: Deploy minimal version to Cloud Run
      run: |
        echo "🚀 Starting minimal deployment..."
        
        set +e  # Don't exit on error so we can capture logs
        
        gcloud run deploy adk-branding-assistant-minimal \
          --source . \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars "PORT=8000" \
          --memory 1Gi \
          --cpu 1 \
          --timeout 3600 \
          --max-instances 5 \
          --verbosity=debug 2>&1 | tee deploy_output.log
        
        DEPLOY_EXIT_CODE=${PIPESTATUS[0]}
        
        if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
          echo "❌ Minimal deployment failed with exit code $DEPLOY_EXIT_CODE"
          echo "🔍 Fetching recent build logs..."
          
          # Get recent builds
          echo "📋 Recent builds:"
          gcloud builds list --limit=5 --format="table(id,status,createTime)" || true
          
          # Get the most recent build logs
          RECENT_BUILD_ID=$(gcloud builds list --limit=1 --format="value(id)" 2>/dev/null || true)
          
          if [ ! -z "$RECENT_BUILD_ID" ]; then
            echo "🔍 Fetching logs for build: $RECENT_BUILD_ID"
            gcloud builds log $RECENT_BUILD_ID || true
          fi
          
          echo "📋 Full deployment output:"
          cat deploy_output.log
          
          exit $DEPLOY_EXIT_CODE
        else
          echo "✅ Minimal deployment successful!"
          
          # Get the service URL
          SERVICE_URL=$(gcloud run services describe adk-branding-assistant-minimal \
              --region us-central1 \
              --format 'value(status.url)')
          
          echo "🌐 Minimal service URL: $SERVICE_URL"
          echo "🔍 Health check: $SERVICE_URL/health"
        fi 